# Default values for icndb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

icndb:
  verticlesCount: 4

image:
  repository: baez90/jericho-victim
  tag: latest
  pullPolicy: Always
resources: {}

postgresql:
  postgresqlUsername: jericho
  postgresqlPassword: 'W@c[3~DV>~:]4%+5"'
  postgresqlDatabase: jericho
  resources:
    requests:
      memory: 256Mi
      cpu: 250m

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - chart-example.local